kind: Deployment
apiVersion: apps/v1
metadata:
  name: cra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cra
  template:
    metadata:
      labels:
        app: cra
    spec:
      containers:
        - name: cra
          image: codehutlabs/cra-runtime-environment-variables
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: cra
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: cra
